name: CI for Landing Page

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  landing-page:
    name: Build & Test Backend (Node.js)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
