name: CD Landing Page

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-lp:
    name: Deploy Landing Page 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy API via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/GreenSpace-AI-LP
            git pull
            npm install
            npm run build
            pm2 reload nextjs-app || pm2 start npm --name "nextjs-app" -- run start
